kind: Service
apiVersion: v1
metadata:
  name: practicaseam
spec:
  selector:
    app: practicaseam
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: practicaseam
  labels:
    app: practicaseam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practicaseam
      tier: backend
  template:
    metadata:
      labels:
        app: practicaseam
        tier: backend
    spec:
      containers:
      - name: practicaseam
        image: gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}   
        ports:
        - name: http
          containerPort: 80
          protocol: TCP